development:
  adapter: postgresql
  encoding: unicode
  database: gtworld_granite_developmennt
  pool: 5
  username: postgres
  password: postgres
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: gtworld_granite_test
  pool: 5
  username: postgres
  password: postgres
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  database: gtworld_granite_production
  pool: 5
  username: postgres
  password: postgres
  host: localhost